version: '3.8'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_data:/var/www/html
    depends_on:
      - db
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./wp_data:/var/www/html
    expose:
      - "9000" # Порт для PHP-FPM

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - ./db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./wp_data:/var/www/html
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - wordpress
      - php


  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/root/.n8n
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=artyom
      - N8N_BASIC_AUTH_PASSWORD=access
      - N8N_URL=https://third.dre.mov:5678
      - N8N_PROTOCOL=https
      - N8N_PORT = 5678
      - N8N_SSL_KEY=/etc/letsencrypt/live/third.dre.mov/privkey.pem
      - N8N_SSL_CERT=/etc/letsencrypt/live/third.dre.mov/fullchain.pem
      - WEBHOOK_URL=https://n8n.third.dre.mov/
    depends_on:
      - db
